import type { Metadata } from 'next';
import { Gavel, Mail } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Review the Terms of Service governing purchases and usage on the Cartora platform.',
};

export default function TermsPage() {
  const lastUpdated = new Date().toLocaleDateString('en-US', {
    month: 'long',
    year: 'numeric',
  });

  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8 space-y-8">
      {/* Header */}
      <div className="border-b pb-6 space-y-2">
        <div className="bg-primary/10 p-2 rounded-lg text-primary w-fit">
          <Gavel className="h-6 w-6" />
        </div>
        <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
          Terms of Service
        </h1>
        <p className="text-muted-foreground text-xs">
          Last updated: {lastUpdated}
        </p>
      </div>

      {/* Content */}
      <div className="text-xs text-muted-foreground space-y-6 leading-relaxed">
        <section className="space-y-2">
          <h2 className="text-sm font-bold text-foreground">1. Introduction & Acceptance</h2>
          <p>
            Welcome to Cartora (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). These Terms of Service govern your access to and use of the Cartora website, multi-vendor shopping carts, review widgets, and checkout services.
          </p>
          <p>
            By creating an account, placing an order, or navigating our catalog, you accept these terms in full. If you do not agree to these terms, please do not use our services.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-foreground">2. User Accounts & Security</h2>
          <p>
            To complete purchases, checkout orders, or leave product reviews, you must register a user account. You are solely responsible for maintaining the confidentiality of your account credentials (email and password).
          </p>
          <p>
            You agree to notify us immediately of any unauthorized use or security leaks. We reserve the right to suspend or terminate accounts that violate our guidelines or engage in fraudulent purchase behaviors.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-foreground">3. Purchases, Billing, & Coupons</h2>
          <p>
            All prices listed on our storefront are in USD. Payment is processed securely through our Stripe credit card sandbox validation engine.
          </p>
          <p>
            Coupons (such as SAVE10 and FLAT15) are subject to individual rules, validity windows, and limits. We reserve the right to modify discount campaigns without notice. Taxes are calculated at a flat 5% rate, and shipping fees are free for orders $\ge 150$, else $15.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-foreground">4. Product Listings, Reviews, & Ratings</h2>
          <p>
            While we strive for extreme catalog accuracy, vendor listings may occasionally contain minor specification discrepancies.
          </p>
          <p>
            Product reviews are generated by our customers. You agree that any comments you write will be honest, respectful, and free of spam, hate speech, or advertising links. We reserve the right to remove comments that violate these guidelines.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-foreground">5. Limitation of Liability</h2>
          <p>
            Cartora provides its catalog on an &quot;as is&quot; basis. We make no guarantees that our storefront will be completely error-free or uninterrupted. In no event shall Cartora be liable for any indirect, incidental, or consequential damages resulting from product purchases.
          </p>
        </section>
      </div>

      {/* Support footer */}
      <div className="text-center text-xs text-muted-foreground pt-6 border-t">
        <p className="flex items-center justify-center gap-1.5">
          <Mail className="h-4 w-4" />
          Need clarification? Contact us at <a href="mailto:legal@cartora.app" className="text-primary hover:underline font-medium">legal@cartora.app</a>.
        </p>
      </div>
    </div>
  );
}
